version: '3.8'

services:
  music-postgres:
    image: postgres:14.5
    container_name: music-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: music-db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - music-postgres-data:/var/lib/postgresql/data

  music-laravel:
    container_name: music-laravel
    image: ${DOCKER_REGISTRY-}music-laravel
    restart: unless-stopped
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      music-postgres:
          condition: service_healthy

  adminer:
    image: adminer:4.8.1
    restart: unless-stopped
    ports:
      - "8088:8080"

volumes:
  music-postgres-data:
